spring:
  application:
    name: drop-in
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.dropin.mybatis.model

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: INFO