server:
  port: 9000

spring:
  application:
    name: drop-in
  datasource:
    url: jdbc:mysql://10.0.2.15:3306/crossfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3307/crossfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.dropin.mybatis.model

jwt:
  issuer: test@gmail.com
  secret_key: O4SxPzNI26ON9JzP9Yx1ffnBKucULNdrUrL0t114BdgRmvKGFGT9RnLp8BP1MG+RosB46Tb6V7WjeSKM/1EN2Q==

logging:
  level:
    org.hibernate.SQL: DEBUG